"use strict";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d");
const modernCanvas=document.querySelector("#modern-text"),modernCtx=modernCanvas.getContext("2d");
ctx.imageSmoothingEnabled=false;
modernCtx.imageSmoothingEnabled=true;modernCtx.setTransform(4,0,0,4,0,0);
const C={ink:"#150d20",panel:"#2b1930",line:"#956b49",paper:"#ead9b7",gold:"#e5b65f",red:"#b64d4b",blue:"#6789b5",green:"#65935c",gray:"#807681",white:"#fff",black:"#09060b",purple:"#68456e"};
const rooms=[
 {name:"CLIFF BASE",x:0,y:2,desc:"A scorched track ends at the cave mouth.",exits:{n:1},props:[{id:"pack",name:"TORCH PACK",x:176,y:112,look:"A leather pack lies beside a still-burning torch."},{id:"tracks",name:"DRAGON TRACKS",x:67,y:73,look:"Claw marks score the rock. Something huge went deeper."}]},
 {name:"BARREN HILLS",x:0,y:1,desc:"Cold wind scours a wall of standing stones.",exits:{s:0,e:2},props:[{id:"tracks",name:"TARQUINE'S TRAIL",x:155,y:91,look:"A knight's crest is stamped in the ash: Sir Tarquine came this way."},{id:"cairn",name:"STONE CAIRN",x:72,y:123,look:"A cairn hides a small purse beneath its lowest stone."}]},
 {name:"JUNCTION",x:1,y:1,desc:"Three passages divide beneath a dead lantern.",exits:{w:1,n:3,e:4},props:[{id:"waystone",name:"WAYSTONE",x:113,y:71,look:"North: the crystal grotto. East: an old hall and a safe resting place."},{id:"pit",name:"COVERED PIT",x:177,y:123,look:"Dust hides a pit trap across the east passage. The loose flagstones mark its edge."}]},
 {name:"CRYSTAL GROTTO",x:1,y:0,desc:"Blue crystals hum beneath a thin veil of mist.",exits:{s:2,e:5},props:[{id:"crystal",name:"BLUE CRYSTAL",x:155,y:67,look:"A fist-sized crystal rings like a tiny bell. It might fit the iron door."},{id:"runes",name:"WALL RUNES",x:72,y:119,look:"The worn inscription says a lightning bolt can turn the dragon seal."}]},
 {name:"ROYAL HALL",x:2,y:1,desc:"A ruined throne watches an empty court.",exits:{w:2,n:5},props:[{id:"shade",name:"OLD SCRIBE",x:158,y:69,look:"A shade remembers Dracobrane: it can kill a dragon, but its hunger can master its bearer."},{id:"innkeeper",name:"INNKEEPER",x:67,y:73,look:"A keeper shelters here. Ten gold buys a healing potion; the throne offers free rest."},{id:"throne",name:"RUINED THRONE",x:187,y:120,look:"The old court is quiet and safe enough to rest and gather your strength."}]},
 {name:"GREAT DOOR",x:2,y:0,desc:"Black iron bears a coiled dragon seal.",exits:{w:3,s:4,e:6},props:[{id:"seal",name:"DRAGON SEAL",x:112,y:68,look:"The sealed door opens to the blue crystal's resonance—or a focused lightning spell."},{id:"door",name:"IRON DOOR",x:113,y:119,look:"Beyond this door lie Tarquine's relics and the dragon's hoard."}]},
 {name:"MUSEUM",x:3,y:0,desc:"Relics stare from shattered, dust-filled cases.",exits:{w:5,s:7},props:[{id:"record",name:"TARQUINE'S RECORD",x:53,y:93,look:"The record names Dracobrane as the only blade that can pierce Doximodius."},{id:"mirror",name:"SILVER MIRROR",x:113,y:93,look:"The dragon draws breath before every third blast. Watch its throat and brace."},{id:"shield",name:"DRAGONFIRE SHIELD",x:174,y:93,look:"A silver shield bears scorch marks but its enchantment still holds."}]},
 {name:"JEWEL ROOM",x:3,y:1,desc:"Coins and gems glow in a million reflections.",exits:{n:6,e:8},props:[{id:"coins",name:"COIN MOUND",x:75,y:107,look:"Silver, copper and gold spill across the floor. There is more than enough."},{id:"sword",name:"DRACOBRANE",x:168,y:75,look:"A golden thread suspends a bright sword above the hoard. It whispers your name."}]},
 {name:"DRAGON LAIR",x:4,y:1,desc:"A red-gold dragon sleeps atop its hoard.",exits:{w:7,s:9},props:[{id:"hoard",name:"GOLDEN HOARD",x:69,y:122,look:"The coins chime softly. The dragon stirs at the sound."},{id:"dragon",name:"DOXIMODIUS",x:169,y:83,look:"The sleeping dragon's throat pulses with fire. Dracobrane hums in your hand."}]},
 {name:"CAMELOT YARD",x:4,y:2,desc:"Three days later, the people gather for Sir Gareth's joust.",exits:{n:8},props:[{id:"gareth",name:"SIR GARETH",x:169,y:91,look:"Gareth offers a friendly rematch. The crowd falls quiet as Dracobrane answers."}]}
];
const enemyBook={GHOUL:{hp:10,pow:4,col:C.gray,xp:220},WRAITH:{hp:13,pow:5,col:C.purple,xp:350},SPECTRE:{hp:15,pow:6,col:C.blue,xp:420},VAMPIRE:{hp:18,pow:7,col:C.red,xp:520},DOXIMODIUS:{hp:48,pow:11,col:C.red,xp:1800,boss:true},GARETH:{hp:26,pow:7,col:C.blue,xp:500,knight:true}};
const roomEncounters={1:"GHOUL",3:"WRAITH",6:"SPECTRE",7:"VAMPIRE"};
let mode="title",storyPage=0,room=0,hp=18,maxhp=18,str=9,intel=8,wis=8,cha=7,xp=0,level=1,gold=0,potions=2,mana=2,maxMana=3,enemy=null,msg="",visited=new Set([0]),cleared=new Set(),escaped=new Set(),guard=false,selected=0,modernText=false;
let flags={},audio=null,muted=false,musicStep=0,musicClock=0,lastFrame=performance.now(),padButtons=[],padDirection="",padRepeat=0;
const textModeButton=document.querySelector("#text-mode");
const graphicsModeButton=document.querySelector("#graphics-mode"),remasterSprites=new RemasterSprites("assets/remaster-sprites-v2.png"),remasterProps=new RemasterSprites("assets/remaster-props.png",5,5),remasterBackgrounds=new RemasterBackgrounds("assets/remaster-backgrounds.png");
let remasterGraphics=false;
function toggleGraphicsMode(){remasterGraphics=!remasterGraphics;graphicsModeButton.textContent=remasterGraphics?"UPDATED GRAPHICS · G":"C64 GRAPHICS · G";graphicsModeButton.setAttribute("aria-pressed",String(remasterGraphics))}
graphicsModeButton.addEventListener("click",toggleGraphicsMode);
addEventListener("message",event=>{if(event.data?.type!=="c64-toggle")return;if(event.data.mode==="text")toggleTextMode();if(event.data.mode==="graphics")toggleGraphicsMode()});
function updateTextModeButton(){textModeButton.textContent=modernText?"MODERN TEXT · T":"C64 TEXT · T";textModeButton.setAttribute("aria-pressed",String(modernText));document.body.classList.toggle("modern-text",modernText)}
function toggleTextMode(){modernText=!modernText;updateTextModeButton()}
textModeButton.addEventListener("click",toggleTextMode);updateTextModeButton();
document.querySelectorAll("[data-touch-key]").forEach(button=>button.addEventListener("click",()=>{wake();press(button.dataset.touchKey)}));
const touchMute=document.querySelector("#touch-mute"),touchPad=document.querySelector(".touch-pad");
touchMute.addEventListener("click",()=>{muted=!muted;touchMute.textContent=`SOUND ${muted?"OFF":"ON"}`});
function wake(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function tone(f,d=.1,w="square",v=.018,end=f,delay=0){if(!audio||muted)return;const t=audio.currentTime+delay,o=audio.createOscillator(),q=audio.createGain();o.type=w;o.frequency.setValueAtTime(Math.max(25,f),t);o.frequency.exponentialRampToValueAtTime(Math.max(25,end),t+d);q.gain.setValueAtTime(.0001,t);q.gain.exponentialRampToValueAtTime(v,t+.008);q.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(q).connect(audio.destination);o.start(t);o.stop(t+d+.02)}
function noise(d=.12,v=.025){if(!audio||muted)return;const n=Math.ceil(audio.sampleRate*d),b=audio.createBuffer(1,n,audio.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=audio.createBufferSource(),q=audio.createGain();s.buffer=b;q.gain.value=v;s.connect(q).connect(audio.destination);s.start()}
function sfx(n){if(n==="step")tone(70,.04,"triangle",.012,55);if(n==="spawn")tone(82,.28,"sawtooth",.035,41);if(n==="hit")tone(190,.08,"square",.035,95);if(n==="hurt"){noise(.08,.02);tone(120,.18,"sawtooth",.03,45)}if(n==="cast")[330,440,554,659].forEach((f,i)=>tone(f,.09,"square",.025,f*1.03,i*.035));if(n==="heal")[262,330,392].forEach((f,i)=>tone(f,.12,"triangle",.03,f,i*.07));if(n==="win")[196,247,294,392].forEach((f,i)=>tone(f,.15,"square",.03,f,i*.08));if(n==="death"){noise(.25,.04);tone(130,.5,"sawtooth",.035,30)}}
addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright"," ","tab","f3"].includes(k))e.preventDefault();wake();if(k==="m"){muted=!muted;return}if(k==="t"){toggleTextMode();return}if(k==="g"){toggleGraphicsMode();return}press(k)});
function reset(){room=0;hp=maxhp=18;str=9;intel=8;wis=8;cha=7;xp=0;level=1;gold=0;potions=2;mana=2;maxMana=3;enemy=null;visited=new Set([0]);cleared=new Set();escaped=new Set();flags={};selected=0;storyPage=0;msg=rooms[0].desc;mode="explore"}
function press(k){
 if(mode==="title"&&(k==="enter"||k===" ")){mode="story";storyPage=0;return}
 if(mode==="story"&&(k==="enter"||k===" ")){if(++storyPage>=4)reset();return}
 if(mode==="dead"&&(k==="enter"||k===" ")){mode="title";return}
 if(mode==="dragonChoice"){if(k==="enter"||k==="g"){room=9;visited.add(9);selected=0;mode="explore";msg="The sword urges Bedivere onward. Sir Gareth awaits in Camelot."}else if(k==="s"){flags.swordSealed=true;mode="win";msg="Bedivere binds Dracobrane beneath the crystal seal and returns to Camelot."}return}
 if(mode==="win"&&(k==="enter"||k===" ")){mode="title";return}
 if(mode==="combat"){
  if(k==="f"||k==="enter"||k===" ")act("fight");else if(k==="c")act("cast");else if(k==="e")act("evade");else if(k==="p")drink();else if(k==="b")act("brace");else if(k==="f3")escapeScroll();return
 }
 if(mode!=="explore")return;
 if(k==="tab"||k==="]"){selected=(selected+1)%roomProps().length;msg=`Selected ${target().name}. Press I to inspect or E to use it.`;return}
 if(k==="["){selected=(selected+roomProps().length-1)%roomProps().length;msg=`Selected ${target().name}. Press I to inspect or E to use it.`;return}
 if(k==="i"){inspect();return}
 if(k==="enter"||k==="e"||k===" "){useProp();return}
 if(k==="r"){rest();return}
 if(k==="v"){inventory();return}
 if(k==="f3"){escapeScroll();return}
 const dir=({w:"n",arrowup:"n",s:"s",arrowdown:"s",a:"w",arrowleft:"w",d:"e",arrowright:"e"})[k];if(dir)travel(dir)
}
function roomProps(){return rooms[room].props}function target(){return roomProps()[selected%roomProps().length]}
function travel(dir){const next=rooms[room].exits[dir];if(next===undefined){msg=`No passage leads ${dir.toUpperCase()} from here.`;return}if(next===6&&!flags.doorOpen){msg="The Great Door bars the way. Use the seal with the blue crystal or lightning.";room=5;selected=0;return}if(next===8&&!flags.sword){msg="The dragon's lair is too dangerous without Dracobrane. The sword waits in the Jewel Room.";return}if(next===9&&!flags.dragonSlain){msg="Camelot lies beyond the dragon. The road home is not yet safe.";return}const pitfall=room===2&&dir==="e"&&!flags.pit&&!flags.pitTriggered;if(pitfall){flags.pitTriggered=true;hp-=4;if(hp<=0){mode="dead";msg="The covered pit gives way. Bedivere falls into the darkness.";return}}room=next;selected=0;visited.add(room);sfx("step");msg=pitfall?"The covered pit gives way. You climb out in the Royal Hall, bruised but alive.":rooms[room].desc;if(room===8&&flags.dragonSlain){msg="The dragon's body lies still. The west passage leads back to Camelot.";return}if(room===9){msg="Three days later, the people gather for Sir Gareth's joust. E to accept.";return}const encounter=roomEncounters[room];if(encounter&&!cleared.has(room)&&!escaped.has(room))spawn(encounter)}
function spawn(name){const base=enemyBook[name];enemy={name,hp:base.hp,max:base.hp,pow:base.pow,col:base.col,xp:base.xp,boss:!!base.boss,knight:!!base.knight,turn:0};mode="combat";msg=`${name==="DOXIMODIUS"?"DOXIMODIUS WAKES":"A "+name+" blocks the way"}. Choose your action.`;sfx("spawn")}
function inspect(){const p=target();msg=`${p.name}: ${p.look}`}
function useProp(){const p=target();switch(p.id){
 case"pack":if(!flags.torch){flags.torch=true;potions++;msg="You take the torch, a healing potion and a rescue scroll. The tunnel is visible now.";flags.scroll=true;sfx("heal")}else msg="The pack is empty. The torch still burns.";break;
 case"tracks":flags.tracks=true;msg="The knight's crest belongs to Sir Tarquine. A broken sword-point lies in the scorched trail.";break;
 case"cairn":if(!flags.cairn){flags.cairn=true;gold+=8;msg="You find 8 gold under the stone. Every coin will help at the inn.";tone(660,.08)}else msg="Only loose stones remain.";break;
 case"waystone":msg="N: Crystal Grotto and a shard. E: Royal Hall, an old scribe and safe rest. Both lead to the Great Door.";break;
 case"pit":if(!flags.pit){flags.pit=true;xp+=100;msg="You wedge the loose flagstone shut. The east passage is safe now.";tone(392,.09,"square",.025,523)}else msg="The pit is safely covered.";break;
 case"crystal":if(!flags.shard){flags.shard=true;maxMana=4;mana=maxMana;msg="The crystal fits your palm and hums. Its light could open the Great Door.";tone(523,.18,"triangle",.035,784)}else msg="The blue crystal answers the runes in your hand.";break;
 case"runes":flags.runeClue=true;msg="The runes describe a lightning bolt that turns the dragon seal. C cast can open it if you have magic.";break;
 case"shade":if(!flags.shade){flags.shade=true;flags.runeClue=true;msg="The scribe whispers: 'Crystal north, or lightning at the seal. Beware the sword; it hungers for its bearer.'"}else msg="The shade repeats: 'A shield for fire. A sword for scales. Keep your will.'";break;
 case"innkeeper":if(gold>=10){gold-=10;potions++;msg="You pay 10 gold for a healing potion. The innkeeper nods.";sfx("heal")}else msg="A healing potion costs 10 gold. Search the cairn or the treasure rooms.";break;
 case"throne":rest();break;
 case"seal":case"door":if(flags.doorOpen)msg="The dragon seal stands open. Beyond lies Tarquine's museum.";else if(flags.shard){flags.doorOpen=true;msg="The blue crystal rings against the seal. The great iron door slowly opens.";sfx("cast")}else if(mana>0){mana--;flags.doorOpen=true;msg="You shape a lightning bolt. The iron seal glows, then releases.";sfx("cast")}else msg="The seal needs the blue crystal from the grotto or one unit of magic. Visit the scribe in the Royal Hall for a clue.";break;
 case"record":flags.record=true;msg="Tarquine's record: 'Dracobrane alone can cut Doximodius. Its bearer must master the blade's hunger.'";break;
 case"mirror":flags.mirror=true;msg="The mirror shows the dragon's throat flare before every third blast. Brace when the fire gathers.";break;
 case"shield":if(!flags.shield){flags.shield=true;msg="You claim the Dragonfire Shield. It will turn most of Doximodius's flame.";tone(392,.1,"triangle",.03,587)}else msg="The shield's silver face catches the torchlight.";break;
 case"coins":if(!flags.coins){flags.coins=true;gold+=40;msg="You gather 40 gold from the bright mound. A low chime wakes the dragon beyond.";tone(784,.08,"square",.02,392)}else msg="A few coins remain, but the pile has been searched.";break;
 case"sword":if(!flags.sword){flags.sword=true;msg="A flash. Dracobrane rests in your hand. 'You are my master. Together we will destroy Doximodius.'";sfx("win")}else msg="Dracobrane whispers for blood. Keep your will.";break;
 case"hoard":if(!flags.hoard){flags.hoard=true;gold+=25;msg="You take 25 gold. The coins ring out. Doximodius opens one molten eye!";spawn("DOXIMODIUS")}else msg="The dragon's vast hoard is yours to search after the battle.";break;
 case"dragon":if(flags.dragonSlain)msg="Doximodius is dead. The sword's glow slowly fades.";else if(!flags.sword)msg="The dragon sleeps. Find Dracobrane in the Jewel Room before you challenge it.";else{flags.dragonAwake=true;msg="You step into the firelight. Dracobrane flares: 'Doximodius!' The dragon wakes.";spawn("DOXIMODIUS")}break;
 case"gareth":if(!flags.garethDone){msg="Gareth lowers his lance. 'A friendly joust, Bedivere. Show me that new blade.'";spawn("GARETH")}else msg="Sir Gareth laughs and clasps your arm. The crowd cheers.";break;
 default:msg=p.look;
 }}
function inventory(){const items=[flags.torch&&"TORCH",flags.shard&&"BLUE CRYSTAL",flags.shield&&"DRAGONFIRE SHIELD",flags.sword&&"DRACOBRANE",flags.scroll&&"RESCUE SCROLL"].filter(Boolean);msg=`PACK: ${items.join(", ")||"empty"}. GOLD ${gold} · POTIONS ${potions} · MAGIC ${mana}/${maxMana}.`}
function escapeScroll(){if(!flags.scroll){msg="No rescue scroll remains.";return}flags.scroll=false;gold=0;enemy=null;mode="explore";room=4;selected=0;visited.add(4);msg="The rescue scroll burns. You wake at the Royal Hall with no gold.";sfx("cast")}
function act(kind){guard=kind==="brace";if(kind==="brace"){msg="You brace and lower your stance to blunt the next blow.";enemyTurn();return}if(kind==="evade"){if(!enemy.boss&&Math.random()<.48+cha*.02){msg=`You slip past the ${enemy.name}. It does not follow.`;escaped.add(room);enemy=null;mode="explore";return}msg="The passage is cut off!";enemyTurn();return}let dmg;if(kind==="cast"){if(mana<=0){msg="No magic remains. Rest in the Royal Hall.";enemyTurn();return}mana--;dmg=7+Math.floor((intel+wis)/4)+Math.floor(Math.random()*3);msg=`LIGHTNING BOLT inflicts ${dmg}.`;sfx("cast")}else{dmg=3+Math.floor(str/3)+Math.floor(Math.random()*3);if(flags.sword)dmg+=5;msg=`${flags.sword?"Dracobrane":"Your blade"} strikes for ${dmg}.`;sfx("hit")}if(enemy.boss&&!flags.sword){msg="Your weapon glances off the dragon's scales. Dracobrane is the only blade that can harm it.";enemyTurn();return}enemy.hp-=dmg;if(enemy.hp<=0){victory();return}enemyTurn()}
function enemyTurn(){if(!enemy)return;enemy.turn++;let damage;if(enemy.boss&&enemy.turn%3===0){damage=flags.shield?5:13;if(flags.mirror)msg+=" The mirror's warning proves true: flame gathers again.";else msg+=" Doximodius draws a deep, burning breath."}else damage=enemy.pow+Math.floor(Math.random()*3);if(guard)damage=Math.ceil(damage/2);if(enemy.boss&&flags.shield&&!guard&&enemy.turn%3!==0)damage=Math.max(1,damage-1);hp-=damage;msg+=` ${enemy.name} hits for ${damage}.`;sfx("hurt");guard=false;if(hp<=0){mode="dead";sfx("death");return}if(enemy.boss&&flags.mirror&&enemy.turn%3===2)msg+=" Fire gathers in its throat—brace with B!"}
function victory(){const name=enemy.name,boss=enemy.boss,reward=enemy.xp;xp+=reward;gold+=boss?0:3+enemy.pow*2;enemy=null;sfx("win");if(boss){flags.dragonSlain=true;mode="dragonChoice";msg="Doximodius falls. Dracobrane urges you toward another enemy. What will you do?";checkLevel();return}cleared.add(room);msg=name==="GARETH"?"Gareth yields. The sword's bloodlust fades; Bedivere vows to master it.":`${name} falls. +${reward} EXP.`;if(name==="GARETH"){flags.garethDone=true;mode="win"}else mode="explore";checkLevel()}
function checkLevel(){const need=level*2000;if(xp>=need&&level<10){level++;maxhp+=3;hp=maxhp;maxMana++;mana=maxMana;str++;if(level%2===0){intel++;wis++}msg+=` LEVEL ${level}! Your wounds close.`}}
function drink(){if(potions<1){msg="No healing potion remains.";if(mode==="combat")enemyTurn();return}potions--;const gain=Math.min(10,maxhp-hp);hp+=gain;msg=`The potion restores ${gain} HP.`;sfx("heal");if(mode==="combat")enemyTurn()}
function rest(){if(room!==4){msg="This place is too dangerous to rest.";return}hp=maxhp;mana=maxMana;msg="You rest beneath the ruined throne. HP and magic restored.";sfx("heal")}
function setTextFont(target,size){const px=modernText&&size<=9?size+3:size;target.font=modernText?`${px}px "Segoe UI", Arial, sans-serif`:`${size}px monospace`}
function text(s,x,y,col=C.paper,size=8,align="left"){const target=modernText?modernCtx:ctx;target.fillStyle=col;setTextFont(target,size);target.textAlign=align;target.fillText(s,x,y)}
function fitText(s,x,y,col,size,maxWidth,align="left",minSize=1){const target=modernText?modernCtx:ctx;let fittedSize=size;setTextFont(target,fittedSize);while(target.measureText(s).width>maxWidth&&fittedSize>minSize){fittedSize--;setTextFont(target,fittedSize)}text(s,x,y,col,fittedSize,align)}
function wrapWords(value,maxWidth,size){const target=modernText?modernCtx:ctx;setTextFont(target,size);const lines=[];let line="";for(const word of String(value).trim().split(/\s+/)){if(!word)continue;let pieces=[word];if(target.measureText(word).width>maxWidth){pieces=[];let part="";for(const char of word){if(part&&target.measureText(part+char).width>maxWidth){pieces.push(part);part=char}else part+=char}if(part)pieces.push(part)}for(const piece of pieces){const next=line?`${line} ${piece}`:piece;if(line&&target.measureText(next).width>maxWidth){lines.push(line);line=piece}else line=next}}if(line)lines.push(line);return lines}
function fitMessage(value,maxWidth,maxLines){let size=7,lines;while(true){lines=wrapWords(value,maxWidth,size);if(lines.length<=maxLines)return{lines,size};size=size>.5?size-.5:size/2}}
function rect(x,y,w,h,col){ctx.fillStyle=col;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function frame(x,y,w,h){rect(x,y,w,h,C.panel);ctx.strokeStyle=C.line;ctx.strokeRect(x+.5,y+.5,w-1,h-1)}
function hero(x,y,s=2){rect(x+4*s,y,3*s,2*s,C.red);rect(x+3*s,y+2*s,5*s,4*s,C.paper);rect(x+2*s,y+6*s,7*s,6*s,C.gray);rect(x,y+6*s,2*s,7*s,C.blue);rect(x+9*s,y+5*s,s,10*s,C.gold);rect(x+2*s,y+12*s,2*s,5*s,C.black);rect(x+7*s,y+12*s,2*s,5*s,C.black)}
function monster(m,x,y,s=2){const n=m.name,col=m.col;if(n==="DOXIMODIUS"){rect(x,y+8*s,15*s,7*s,col);rect(x+11*s,y+3*s,8*s,7*s,col);rect(x+17*s,y+4*s,2*s,2*s,C.gold);rect(x+3*s,y+2*s,8*s,6*s,col);rect(x+1*s,y,4*s,4*s,C.red);rect(x+6*s,y,4*s,4*s,C.red);rect(x+19*s,y+6*s,5*s,2*s,C.gold);return}if(n==="GARETH"){hero(x,y,s);rect(x+22*s,y+3*s,2*s,19*s,C.line);rect(x+18*s,y+4*s,9*s,2*s,C.gold);return}if(n==="WRAITH"||n==="SPECTRE"){rect(x+3*s,y,6*s,5*s,col);rect(x+2*s,y+5*s,8*s,7*s,col);rect(x,y+12*s,12*s,2*s,col);rect(x+4*s,y+2*s,s,s,C.white);rect(x+7*s,y+2*s,s,s,C.white);if(n==="SPECTRE"){rect(x-s,y+5*s,3*s,2*s,C.blue);rect(x+10*s,y+8*s,4*s,2*s,C.blue)}return}rect(x+3*s,y,6*s,5*s,col);rect(x+2*s,y+5*s,8*s,8*s,col);rect(x,y+6*s,2*s,7*s,col);rect(x+10*s,y+6*s,2*s,7*s,col);rect(x+3*s,y+13*s,2*s,4*s,C.black);rect(x+7*s,y+13*s,2*s,4*s,C.black);rect(x+4*s,y+2*s,s,s,C.white);rect(x+7*s,y+2*s,s,s,C.white)}
function propIcon(p){const x=p.x,y=p.y,id=p.id,sel=target()===p;if(sel){ctx.strokeStyle=C.gold;ctx.strokeRect(x-17,y-18,34,35)}if(id==="pack"){rect(x-9,y-8,18,17,"#76492b");rect(x-6,y-11,12,4,C.gold);rect(x+6,y-17,2,9,C.gold);rect(x+4,y-19,6,3,C.red)}else if(id==="tracks"){rect(x-13,y-4,26,3,C.red);rect(x-7,y-9,4,4,C.red);rect(x+4,y-9,4,4,C.red)}else if(id==="cairn"||id==="pit"){rect(x-12,y-4,24,7,C.gray);rect(x-7,y-9,15,5,"#aaa6a0")}else if(id==="crystal"){rect(x-4,y-14,8,21,C.blue);rect(x-9,y-4,18,5,"#9bd5eb");rect(x-3,y-11,3,7,C.white)}else if(id==="runes"||id==="seal"){rect(x-14,y-12,28,24,C.black);ctx.strokeStyle=C.gold;ctx.strokeRect(x-13,y-11,26,22);text("ᛟ",x,y+4,C.gold,14,"center")}else if(id==="throne"){rect(x-13,y-8,26,13,C.gray);rect(x-11,y-15,22,8,C.gold);rect(x-9,y+5,4,7,C.gray);rect(x+5,y+5,4,7,C.gray)}else if(id==="shade"){rect(x-8,y-12,16,21,C.purple);rect(x-4,y-16,8,6,C.gray);rect(x-3,y-7,2,2,C.white);rect(x+3,y-7,2,2,C.white)}else if(id==="innkeeper"){rect(x-5,y-15,10,9,C.paper);rect(x-8,y-6,16,15,C.green);rect(x-11,y+2,22,3,C.line);rect(x-3,y-12,2,2,C.black);rect(x+2,y-12,2,2,C.black)}else if(id==="record"){rect(x-12,y-12,24,22,C.gold);rect(x-9,y-9,18,2,C.black);rect(x-9,y-4,15,2,C.black);rect(x-9,y+1,18,2,C.black)}else if(id==="mirror"){rect(x-9,y-14,18,26,C.blue);rect(x-5,y-10,10,18,"#d6e9ef");rect(x-3,y-7,4,7,C.white)}else if(id==="shield"){rect(x-11,y-14,22,23,C.gray);rect(x-7,y-10,14,15,C.blue);rect(x-2,y-6,4,9,C.gold)}else if(id==="coins"||id==="hoard"){for(let i=0;i<5;i++)rect(x-14+i*6,y-4-(i%2)*4,8,7,i%2?C.gold:"#d8b64f")}else if(id==="sword"){rect(x-1,y-15,3,23,C.white);rect(x-7,y-3,15,3,C.gold);rect(x-2,y+8,5,7,C.line)}else if(id==="dragon"){monster({name:"DOXIMODIUS",col:C.red},x-17,y-15,1)}else if(id==="gareth"){hero(x-7,y-13,1);rect(x+7,y-7,2,20,C.gold)}text(p.name.slice(0,11),x,y+24,sel?C.gold:C.white,5,"center")}
function scene(){frame(5,27,220,151);rect(11,33,208,139,"#23172b");const r=room;if(r===0){rect(11,126,208,46,"#594331");for(let i=0;i<6;i++)rect(22+i*35,112-i%2*8,24,6,C.gray)}if(r===1){rect(11,33,208,139,"#493244");for(let i=0;i<7;i++){rect(20+i*29,62+(i%2)*20,5,88,C.gray);rect(16+i*29,57+(i%2)*20,13,7,C.gray)}}if(r===2){rect(100,33,28,139,"#3b2d38");rect(11,84,208,29,"#3b2d38");rect(107,39,14,127,C.gray)}if(r===3){for(let i=0;i<18;i++){const xx=15+(i*31)%195,yy=38+(i*47)%120;rect(xx,yy,4,12,i%2?C.blue:"#8ca9c7");rect(xx-2,yy+3,8,4,i%2?C.blue:"#8ca9c7")}}if(r===4){rect(11,118,208,54,"#4b343b");rect(91,74,47,39,C.line);rect(99,62,31,13,C.gold);for(let i=0;i<5;i++)rect(20+i*43,48,7,93,C.gray)}if(r===5){rect(68,39,95,130,C.black);ctx.strokeStyle=C.line;ctx.strokeRect(69,40,93,128);for(let yy=48;yy<162;yy+=15)for(let xx=78;xx<155;xx+=18)rect(xx,yy,5,5,C.line)}if(r===6){for(let i=0;i<3;i++){rect(20+i*67,53,55,89,"#463341");ctx.strokeStyle=C.blue;ctx.strokeRect(22+i*67,55,51,85);rect(29+i*67,124,36,5,C.gold)}}if(r===7){for(let i=0;i<46;i++){const xx=14+(i*37)%201,yy=63+(i*19)%99;rect(xx,yy,3,3,i%3?C.gold:C.white)}}if(r===8){rect(11,120,208,52,"#471c20");for(let i=0;i<32;i++)rect(14+(i*29)%200,107+(i*13)%57,4,4,i%2?C.gold:C.red)}if(r===9){rect(11,120,208,52,"#594331");rect(30,52,35,88,C.gray);rect(34,48,27,11,C.gold);rect(160,70,34,7,C.gray)}hero(31,102,2);for(const p of roomProps())propIcon(p);if(enemy)monster(enemy,145,72,2);drawExits()}
function drawExits(){const e=rooms[room].exits;if(e.n!==undefined)text("N",115,40,C.white,7,"center");if(e.s!==undefined)text("S",115,169,C.white,7,"center");if(e.w!==undefined)text("W",15,94,C.white,7);if(e.e!==undefined)text("E",216,94,C.white,7,"right")}
function minimap(){frame(230,27,85,84);text("MAP",272,38,C.gold,7,"center");for(let i=0;i<rooms.length;i++){if(!visited.has(i)&&i!==room)continue;const r=rooms[i],mx=238+r.x*14,my=49+r.y*17;for(const d in r.exits){const q=rooms[r.exits[d]],qx=238+q.x*14,qy=49+q.y*17;ctx.strokeStyle="#574052";ctx.beginPath();ctx.moveTo(mx+4,my+3);ctx.lineTo(qx+4,qy+3);ctx.stroke()}rect(mx,my,8,7,i===room?C.gold:C.gray);if(i===room)rect(mx+3,my+2,3,3,C.red)}text("YOU",272,104,C.paper,6,"center")}
function hud(){frame(5,4,310,19);fitText(`${rooms[room].name} HP ${hp}/${maxhp} LV ${level} GOLD ${gold}`,10,17,C.white,7,300);minimap();frame(230,115,85,62);text("SIR BEDIVERE",272,126,C.gold,7,"center");text(`STR ${str} INT ${intel}`,236,138,C.paper,6);text(`WIS ${wis} CHA ${cha}`,236,148,C.paper,6);text(`EXP ${xp}`,236,164,C.paper,6);frame(5,181,310,54);const fitted=fitMessage(msg,mode==="combat"?240:298,3),rows=[190,200,210];fitted.lines.forEach((line,i)=>text(line,11,rows[i],C.white,fitted.size));if(mode==="combat"){fitText("ENTER/F/A FIGHT · C/X CAST · B KEY/PAD BRACE",11,222,C.gold,6,298);fitText("E KEY/LB EVADE · P/Y POTION · F3/RB SCROLL",11,231,C.gold,6,298);text(`${enemy.name} ${Math.max(0,enemy.hp)}/${enemy.max}`,315,194,C.red,6,"right")}else if(mode==="explore"){const p=target();fitText(`TARGET ${p.name} · ENTER/E/A USE · TAB/B NEXT`,11,222,C.gold,6,298);fitText("ARROWS/D-PAD MOVE · I/X LOOK · V/Y PACK · F3/RB SCROLL",11,231,C.gold,6,298)}else if(mode==="dragonChoice"){fitText("ENTER/A RIDE TO CAMELOT · S/B SEAL SWORD",11,225,C.gold,6,298)}else{fitText("ENTER/A CONTINUE",11,225,C.gold,6,298)}}
function title(){rect(0,0,320,240,C.ink);text("DOXIMODIUS",160,79,C.gold,28,"center");text("THE SWORD BENEATH THE HILLS",160,102,C.red,8,"center");monster({name:"DOXIMODIUS",col:C.red},209,124,2);hero(54,131,2);text("PRESS ENTER / A",160,180,C.white,9,"center");text("T TEXT: C64 / MODERN",160,203,C.gold,7,"center");text("A NOTEBOOK RPG BY MICHAEL KING",160,226,"#715b68",7,"center")}
const storyText=[[
 "AT CAMELOT'S JOUST, SIR GARETH",
 "BROKE BEDIVERE'S SWORD. HE VOWED",
 "TO FIND A WEAPON WORTHY OF A KNIGHT.","",
 "A RUINED VILLAGE POINTED HIM NORTH."
],[
 "THE PEOPLE SPOKE OF DOXIMODIUS,",
 "WHO STOLE A GREAT SWORD FROM TARQUINE.",
 "DRACOBRANE COULD SLAY THE DRAGON,",
 "BUT IT HUNGERED FOR BLOOD—EVEN",
 "THE BLOOD OF ITS OWN GOOD MASTER."
],[
 "AFTER TWO DAYS IN THE HILLS,",
 "BEDIVERE FOUND A CHARRED CAVE.",
 "A TORCH LIT THE NARROW PASSAGE.",
 "SOMEWHERE BELOW, A SWORD AWAITED."
],[
 "YOUR QUEST: FIND DRACOBRANE.",
 "SEARCH THE RELICS FOR A FIRE SHIELD.",
 "THEN FACE DOXIMODIUS—AND KEEP",
 "YOUR OWN WILL. EXPLORE EACH ROOM",
 "WITH E TO USE AND I TO INSPECT."
]];
function story(){rect(0,0,320,240,C.ink);text("THE CHRONICLE",160,46,C.gold,13,"center");storyText[storyPage].forEach((s,i)=>text(s,160,78+i*17,i===0?C.paper:C.white,8,"center"));text(`${storyPage+1} / ${storyText.length} · ENTER / A`,160,202,C.gold,8,"center")}
function choice(){rect(0,0,320,240,C.ink);text("THE DRAGON IS SLAIN",160,76,C.gold,16,"center");text("DRACOBRANE WHISPERS: 'LET US FIND",160,108,C.paper,8,"center");text("ANOTHER ENEMY. THERE ARE MANY.'",160,122,C.paper,8,"center");text("ENTER / A  RIDE TO CAMELOT AND FACE GARETH",160,160,C.white,7,"center");text("S / B  SEAL THE SWORD BENEATH THE HILLS",160,178,C.white,7,"center")}
function ending(){rect(0,0,320,240,C.ink);text(mode==="dead"?"SIR BEDIVERE HAS FALLEN":"THE JOUST IS DONE",160,84,mode==="dead"?C.red:C.gold,16,"center");const lines=mode==="dead"?["THE SWORD WAITS IN DARKNESS.","PRESS ENTER / A TO TRY AGAIN."]:["THE CROWD CHEERS FOR BEDIVERE.","BUT THE SWORD STILL WHISPERS.","'A GOOD KNIGHT MUST MASTER ME.'","THE QUEST IS COMPLETE."];lines.forEach((s,i)=>text(s,160,116+i*17,C.paper,8,"center"));if(mode==="dead")text("PRESS ENTER / A",160,184,C.white,8,"center")}
function music(dt){if(!audio||muted)return;musicClock-=dt;if(musicClock>0)return;const lead=[220,262,330,294,220,196,247,294,165,196,247,220,147,165,196,247],bass=[55,55,65,65,49,49,55,55],f=lead[musicStep%lead.length],b=bass[Math.floor(musicStep/2)%bass.length];tone(f,.15,"square",.011);tone(f*(musicStep%4===3?1.5:1.25),.055,"square",.006);if(musicStep%2===0)tone(b,.38,"triangle",.018);if(musicStep%4===2)noise(.035,.006);musicStep++;musicClock=.19}
function gamepadFrame(dt){if(!navigator.getGamepads)return;const pad=[...navigator.getGamepads()].find(p=>p&&p.connected);if(!pad){padButtons=[];padDirection="";padRepeat=0;return}const pressed=i=>!!pad.buttons[i]?.pressed;let dir="";if(pressed(12))dir="arrowup";else if(pressed(13))dir="arrowdown";else if(pressed(14))dir="arrowleft";else if(pressed(15))dir="arrowright";else{const ax=pad.axes[0]||0,ay=pad.axes[1]||0;if(Math.abs(ax)>.55||Math.abs(ay)>.55)dir=Math.abs(ax)>Math.abs(ay)?(ax<0?"arrowleft":"arrowright"):(ay<0?"arrowup":"arrowdown")}padRepeat-=dt;if(dir&&mode==="explore"&&(dir!==padDirection||padRepeat<=0)){wake();press(dir);padRepeat=.23}if(!dir)padRepeat=0;padDirection=dir;const now=pad.buttons.map(b=>!!b.pressed),just=i=>now[i]&&!padButtons[i];if(just(0)){wake();press("enter")}if(just(1)){wake();if(mode==="dragonChoice")press("s");else if(mode==="explore")press("tab");else if(mode==="combat")press("b")}if(just(2)){wake();if(mode==="explore")press("i");else if(mode==="combat")press("c")}if(just(3)){wake();if(mode==="explore")press("v");else if(mode==="combat")press("p")}if(just(4)){wake();if(mode==="explore")press("r");else if(mode==="combat")press("e")}if(just(5)){wake();press("f3")}padButtons=now}
const c64Hero=hero,c64Monster=monster,c64PropIcon=propIcon,c64Scene=scene;
hero=function(x,y,s=2){if(!remasterGraphics||!remasterSprites.draw(ctx,0,x-3,y-5,22,30))c64Hero(x,y,s)};
monster=function(m,x,y,s=2){
  if(!remasterGraphics){c64Monster(m,x,y,s);return}
  const tile=({DOXIMODIUS:1,GARETH:6,WRAITH:2,SPECTRE:3,GHOUL:4,VAMPIRE:5})[m.name]??4;
  if(!remasterSprites.draw(ctx,tile,x-3,y-5,tile===1?48:24,tile===1?39:30))c64Monster(m,x,y,s);
};
const propTiles={pack:0,tracks:1,cairn:2,pit:3,crystal:4,runes:5,waystone:6,shade:7,innkeeper:8,throne:9,seal:10,door:11,record:12,mirror:13,shield:14,coins:15,hoard:16,sword:17,dragon:18,gareth:19};
propIcon=function(p){
  if(!remasterGraphics||!remasterProps.ready){c64PropIcon(p);return}
  const x=p.x,y=p.y,selectedProp=target()===p,tile=propTiles[p.id];
  if(selectedProp){ctx.strokeStyle=C.gold;ctx.strokeRect(x-16,y-18,33,36)}
  if(tile!==undefined)remasterProps.draw(ctx,tile,x-10,y-14,21,22);
  rect(x-22,y+14,44,11,C.panel);
  fitText(p.name.slice(0,11),x,y+22,selectedProp?C.gold:C.white,5,42,"center");
};
scene=function(){
  if(!remasterGraphics||!remasterBackgrounds.ready){c64Scene();return}
  frame(5,27,220,151);
  const backdrop=[0,0,0,1,2,2,2,3,3,2][room];
  remasterBackgrounds.draw(ctx,backdrop,11,33,208,139);
  rect(11,33,208,139,"#130c1e44");
  hero(31,102,2);
  for(const prop of roomProps())propIcon(prop);
  if(enemy)monster(enemy,145,72,2);
  drawExits();
};
function draw(now=performance.now()){const dt=Math.min(.05,(now-lastFrame)/1000);lastFrame=now;gamepadFrame(dt);music(dt);document.body.dataset.gameMode=mode;touchPad.style.display=mode==="explore"?"grid":"none";document.querySelector("#touch-primary").textContent=({title:"START ADVENTURE",story:"CONTINUE",explore:"USE / ENTER",combat:"ATTACK",dragonChoice:"RIDE TO CAMELOT",dead:"TRY AGAIN",win:"CONTINUE"})[mode]||"CONTINUE";touchMute.textContent=`SOUND ${muted?"OFF":"ON"}`;if(modernText)modernCtx.clearRect(0,0,320,240);rect(0,0,320,240,C.ink);if(mode==="title")title();else if(mode==="story")story();else if(mode==="dead"||mode==="win")ending();else if(mode==="dragonChoice")choice();else{scene();hud()}requestAnimationFrame(draw)}draw();
