"use strict";
const touchStyle=document.createElement("style");touchStyle.textContent=`.touch-controls{display:none}@media(max-width:720px),(pointer:coarse){.touch-controls{display:grid;gap:8px;margin:14px auto;padding:10px;max-width:100%;border:1px solid #8f83d7;background:#211a63}.touch-controls button{min-width:48px;min-height:48px;touch-action:manipulation;user-select:none;-webkit-user-select:none}.organ-controls{grid-template-columns:repeat(3,minmax(0,1fr))}.maze-controls{grid-template-columns:1fr auto;align-items:center}.maze-controls .touch-pad{display:grid;grid-template-columns:repeat(3,50px);grid-template-rows:repeat(3,48px);gap:4px}.maze-controls .pad-center{display:grid;place-items:center;color:#8f83d7}.maze-controls [data-maze-move="n"]{min-width:110px}.piano{touch-action:pan-x}.app.active{overflow-x:hidden}}@media(max-width:480px){main{margin:8px auto;padding:12px;border-width:7px}.maze-controls{grid-template-columns:1fr}.maze-controls [data-maze-move="n"]{width:100%}.piano{height:154px}.key{height:140px;padding:108px 2px 0;font-size:11px}.key:nth-child(2),.key:nth-child(4),.key:nth-child(7){height:92px;padding:62px 2px 0;margin:0 -10px}}`;document.head.append(touchStyle);
let audio=null,muted=false,oct=3,wave="square",active="home",modernText=false;
const textModeButton=document.querySelector("#text-mode");
function updateTextModeButton(){textModeButton.textContent=modernText?"MODERN TEXT · T":"C64 TEXT · T";textModeButton.setAttribute("aria-pressed",String(modernText));document.body.classList.toggle("modern-text",modernText)}
function toggleTextMode(){modernText=!modernText;updateTextModeButton()}
textModeButton.addEventListener("click",toggleTextMode);updateTextModeButton();
function wake(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function tone(f,d=.22,w=wave,v=.04,end=f){if(!audio||muted)return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=w;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,end),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(v,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(audio.destination);o.start();o.stop(t+d+.02)}
function noise(){if(!audio||muted)return;const n=audio.sampleRate*.12,b=audio.createBuffer(1,n,audio.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=audio.createBufferSource(),g=audio.createGain();s.buffer=b;g.gain.value=.055;s.connect(g).connect(audio.destination);s.start()}
function show(id){active=id;document.querySelectorAll(".app").forEach(x=>x.classList.toggle("active",x.id===id));if(id==="maze")drawMaze()}
document.querySelectorAll("[data-app]").forEach(b=>b.onclick=()=>show(b.dataset.app));document.querySelector("#mute").onclick=e=>{muted=!muted;e.target.textContent=`M SOUND ${muted?"OFF":"ON"}`};
const noteKeys="asdfghjk",names=["C","D","E","F","G","A","B","C"],semi=[0,2,4,5,7,9,11,12],keys=document.querySelector("#keys");
semi.forEach((n,i)=>{const b=document.createElement("button");b.className="key";b.textContent=`${names[i]}\n${noteKeys[i].toUpperCase()}`;b.onpointerdown=()=>playNote(i,b);keys.append(b)});
function playNote(i,b){wake();const f=16.3516*2**(oct+semi[i]/12);tone(f,.35);b.classList.add("active");setTimeout(()=>b.classList.remove("active"),150)}
function setVoice(){document.querySelector("#octave").textContent=oct;document.querySelector("#wave").textContent=wave.toUpperCase()}
const organControls=document.createElement("div");organControls.className="touch-controls organ-controls";organControls.setAttribute("aria-label","Organ touch controls");organControls.innerHTML='<button type="button" data-octave="-1">OCTAVE −</button><button type="button" data-octave="1">OCTAVE +</button><button type="button" data-wave="square">SQUARE</button><button type="button" data-wave="sawtooth">SAW</button><button type="button" data-wave="triangle">TRIANGLE</button><button type="button" data-drum>DRUM</button>';document.querySelector("#keys").after(organControls);
const mazeControls=document.createElement("div");mazeControls.className="touch-controls maze-controls";mazeControls.setAttribute("aria-label","Labyrinth touch controls");mazeControls.innerHTML='<div class="touch-pad" role="group" aria-label="Move in the maze"><span></span><button type="button" data-maze-move="arrowup" aria-label="Move north">▲</button><span></span><button type="button" data-maze-move="arrowleft" aria-label="Move west">◀</button><span class="pad-center" aria-hidden="true">◆</span><button type="button" data-maze-move="arrowright" aria-label="Move east">▶</button><span></span><button type="button" data-maze-move="arrowdown" aria-label="Move south">▼</button><span></span></div><button type="button" data-maze-move="n">NEW MAZE</button>';document.querySelector("#mazeStatus").after(mazeControls);
document.querySelectorAll("[data-octave]").forEach(button=>button.onclick=()=>{wake();oct=Math.max(1,Math.min(6,oct+Number(button.dataset.octave)));setVoice()});document.querySelectorAll("[data-wave]").forEach(button=>button.onclick=()=>{wake();wave=button.dataset.wave;setVoice()});document.querySelector("[data-drum]").onclick=()=>{wake();noise()};document.querySelectorAll("[data-maze-move]").forEach(button=>button.onclick=()=>{wake();mazeKey(button.dataset.mazeMove)});
addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(active==="maze"&&["arrowup","arrowdown","arrowleft","arrowright"].includes(k))e.preventDefault();if(active==="organ"&&k===" ")e.preventDefault();wake();if(k==="m"){document.querySelector("#mute").click();return}if(k==="t"){toggleTextMode();return}if(["f1","f3","f5","f7"].includes(k)){e.preventDefault();show({f1:"home",f3:"organ",f5:"maze",f7:"lemon"}[k]);return}if(active==="organ"){const i=noteKeys.indexOf(k);if(i>=0)playNote(i,keys.children[i]);if(k==="z")oct=Math.max(1,oct-1);if(k==="x")oct=Math.min(6,oct+1);if(k==="1")wave="square";if(k==="2")wave="sawtooth";if(k==="3")wave="triangle";if(k===" ")noise();setVoice()}if(active==="maze")mazeKey(k)});
const mc=document.querySelector("#mazeCanvas"),mg=mc.getContext("2d");mg.imageSmoothingEnabled=false;const MW=20,MH=12;let maze,mp,moves=0;
function newMaze(){maze=Array.from({length:MH},()=>Array.from({length:MW},()=>({v:false,w:[1,1,1,1]})));const stack=[[0,0]];maze[0][0].v=true;while(stack.length){const [x,y]=stack.at(-1),opts=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]].filter(([dx,dy])=>maze[y+dy]?.[x+dx]&&!maze[y+dy][x+dx].v);if(!opts.length){stack.pop();continue}const [dx,dy,a,b]=opts[Math.floor(Math.random()*opts.length)],q=maze[y+dy][x+dx];maze[y][x].w[a]=q.w[b]=0;q.v=true;stack.push([x+dx,y+dy])}mp={x:0,y:0};moves=0;drawMaze()}
function line(a,b,c,d){mg.beginPath();mg.moveTo(a,b);mg.lineTo(c,d);mg.stroke()}
function drawMaze(){if(!maze)return;mg.fillStyle="#11102d";mg.fillRect(0,0,320,200);const sx=16,sy=16;mg.strokeStyle="#93a6ff";mg.lineWidth=2;for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){const c=maze[y][x],X=x*sx,Y=y*sy;if(c.w[0])line(X,Y,X+sx,Y);if(c.w[1])line(X+sx,Y,X+sx,Y+sy);if(c.w[2])line(X,Y+sy,X+sx,Y+sy);if(c.w[3])line(X,Y,X,Y+sy)}mg.fillStyle=Math.floor(performance.now()/300)%2?"#efff79":"#e96c65";mg.fillRect(306,178,10,10);mg.fillStyle="#fff";mg.fillRect(mp.x*sx+5,mp.y*sy+4,7,8);document.querySelector("#mazeStatus").textContent=`MOVES ${moves} · EXIT ${MW},${MH}`}
function mazeKey(k){if(k==="n"){newMaze();return}const dir=({w:0,arrowup:0,d:1,arrowright:1,s:2,arrowdown:2,a:3,arrowleft:3})[k];if(dir===undefined||maze[mp.y][mp.x].w[dir])return;const d=[[0,-1],[1,0],[0,1],[-1,0]][dir];mp.x+=d[0];mp.y+=d[1];moves++;tone(90,.035,"triangle",.015,70);drawMaze();if(mp.x===MW-1&&mp.y===MH-1){document.querySelector("#mazeStatus").textContent=`ESCAPED IN ${moves} MOVES! PRESS N`;[262,330,392,523].forEach((f,i)=>setTimeout(()=>tone(f,.12),i*70))}}
newMaze();
let day=1,cash=20,weather="SUNNY";const ledger=document.querySelector("#ledger");function forecast(){weather=["HOT","SUNNY","CLOUDY","RAINY"][Math.floor(Math.random()*4)];document.querySelector("#forecast").textContent=`DAY ${day}/7 · ${weather} · CASH $${cash.toFixed(2)}`;if(!ledger.textContent)ledger.textContent="THE STAND IS READY.\nLEMONADE COSTS 8¢ PER CUP."}
document.querySelector("#sell").onclick=()=>{wake();if(day>7)return;const price=+document.querySelector("#price").value/100,cups=+document.querySelector("#cups").value,ads=+document.querySelector("#ads").value,cost=cups*.08+ads;if(cost>cash){ledger.textContent="NOT ENOUGH CASH FOR THAT PLAN.";tone(90,.2,"sawtooth",.03,45);return}const boost={HOT:1.5,SUNNY:1.2,CLOUDY:.8,RAINY:.45}[weather],demand=Math.max(0,Math.round((34-price*65+ads*5)*boost*(.8+Math.random()*.4))),sold=Math.min(cups,demand),profit=sold*price-cost;cash+=profit;ledger.textContent=`DAY ${day}: ${weather}\nMADE ${cups} CUPS\nSOLD ${sold} @ ${Math.round(price*100)}¢\nCOST $${cost.toFixed(2)}\nPROFIT $${profit.toFixed(2)}\nCASH $${cash.toFixed(2)}`;tone(profit>=0?523:110,.18,profit>=0?"square":"sawtooth",.025,profit>=0?784:55);day++;if(day>7)ledger.textContent+=`\n\nWEEK COMPLETE: $${cash.toFixed(2)}\n${cash>=35?"A THRIVING STAND!":"TRY A NEW STRATEGY."}`;else forecast()};forecast();
